name: Release Charts
on:
  push:
    branches:
      - 'test_app_version'
    tags:
      - 'v*'
    paths:
      - 'install/kubernetes/**'
jobs:
  release-chart:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v3
      - name: set env
        id: vars
        run: echo ::set-output name=tag::${{ github.ref_name }}
      - name: Publish Helm chart for release version
        run: echo ${{ steps.vars.outputs.tag }}