name: Release Charts
on:
  push:
    branches:
      - 'test_app_version'
    tags:
      - 'v*'
    paths:
      - 'install/kubernetes/**'
jobs:
  release-chart:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v3
      - name: set env
        id: vars
        # https://github.community/t/how-to-get-just-the-tag-name/16241/7
        run: echo ${GITHUB_REF/refs\/tags\//} && echo ${{ github.ref_name }}